/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Moosend.Wrappers.CSharpWrapper.Client.SwaggerDateConverter;

namespace Moosend.Wrappers.CSharpWrapper.Model
{
    /// <summary>
    /// Context132
    /// </summary>
    [DataContract]
    public partial class Context132 :  IEquatable<Context132>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Context132" /> class.
        /// </summary>
        /// <param name="A">A.</param>
        /// <param name="B">B.</param>
        /// <param name="CampaignID">.</param>
        public Context132(A A = default(A), B B = default(B), string CampaignID = default(string))
        {
            this.A = A;
            this.B = B;
            this.CampaignID = CampaignID;
        }
        
        /// <summary>
        /// Gets or Sets A
        /// </summary>
        [DataMember(Name="A", EmitDefaultValue=false)]
        public A A { get; set; }

        /// <summary>
        /// Gets or Sets B
        /// </summary>
        [DataMember(Name="B", EmitDefaultValue=false)]
        public B B { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="CampaignID", EmitDefaultValue=false)]
        public string CampaignID { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Context132 {\n");
            sb.Append("  A: ").Append(A).Append("\n");
            sb.Append("  B: ").Append(B).Append("\n");
            sb.Append("  CampaignID: ").Append(CampaignID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Context132);
        }

        /// <summary>
        /// Returns true if Context132 instances are equal
        /// </summary>
        /// <param name="other">Instance of Context132 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Context132 other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.A == other.A ||
                    this.A != null &&
                    this.A.Equals(other.A)
                ) && 
                (
                    this.B == other.B ||
                    this.B != null &&
                    this.B.Equals(other.B)
                ) && 
                (
                    this.CampaignID == other.CampaignID ||
                    this.CampaignID != null &&
                    this.CampaignID.Equals(other.CampaignID)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.A != null)
                    hash = hash * 59 + this.A.GetHashCode();
                if (this.B != null)
                    hash = hash * 59 + this.B.GetHashCode();
                if (this.CampaignID != null)
                    hash = hash * 59 + this.CampaignID.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
