/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Moosend.Wrappers.CSharpWrapper.Client.SwaggerDateConverter;

namespace Moosend.Wrappers.CSharpWrapper.Model
{
    /// <summary>
    /// CreatingACustomFieldRequest
    /// </summary>
    [DataContract]
    public partial class CreatingACustomFieldRequest :  IEquatable<CreatingACustomFieldRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreatingACustomFieldRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreatingACustomFieldRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreatingACustomFieldRequest" /> class.
        /// </summary>
        /// <param name="Name">The name of the custom field. (required).</param>
        /// <param name="CustomFieldType">Specifies the data type of the custom field. This must be one of the following values. If omitted, Text will be assumed. * &#x60;Text&#x60; * &#x60;Decimal&#x60; * &#x60;DateTime&#x60; * &#x60;SingleSelectDropdown&#x60; * &#x60;Integer&#x60; * &#x60;CheckBox&#x60;.</param>
        /// <param name="Options">If you want to create a custom field of type SingleSelectDropdown, you must set this parameter to specify the available options for the user to choose from. Use a comma (,) to separate different options..</param>
        /// <param name="IsRequired">Specify whether this is field will be mandatory on not, when being used in a subscription form. You should specify a value of either true or false. If omitted, false will be assumed..</param>
        public CreatingACustomFieldRequest(string Name = default(string), string CustomFieldType = default(string), string Options = default(string), string IsRequired = default(string))
        {
            // to ensure "Name" is required (not null)
            if (Name == null)
            {
                throw new InvalidDataException("Name is a required property for CreatingACustomFieldRequest and cannot be null");
            }
            else
            {
                this.Name = Name;
            }
            this.CustomFieldType = CustomFieldType;
            this.Options = Options;
            this.IsRequired = IsRequired;
        }
        
        /// <summary>
        /// The name of the custom field.
        /// </summary>
        /// <value>The name of the custom field.</value>
        [DataMember(Name="Name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Specifies the data type of the custom field. This must be one of the following values. If omitted, Text will be assumed. * &#x60;Text&#x60; * &#x60;Decimal&#x60; * &#x60;DateTime&#x60; * &#x60;SingleSelectDropdown&#x60; * &#x60;Integer&#x60; * &#x60;CheckBox&#x60;
        /// </summary>
        /// <value>Specifies the data type of the custom field. This must be one of the following values. If omitted, Text will be assumed. * &#x60;Text&#x60; * &#x60;Decimal&#x60; * &#x60;DateTime&#x60; * &#x60;SingleSelectDropdown&#x60; * &#x60;Integer&#x60; * &#x60;CheckBox&#x60;</value>
        [DataMember(Name="CustomFieldType", EmitDefaultValue=false)]
        public string CustomFieldType { get; set; }

        /// <summary>
        /// If you want to create a custom field of type SingleSelectDropdown, you must set this parameter to specify the available options for the user to choose from. Use a comma (,) to separate different options.
        /// </summary>
        /// <value>If you want to create a custom field of type SingleSelectDropdown, you must set this parameter to specify the available options for the user to choose from. Use a comma (,) to separate different options.</value>
        [DataMember(Name="Options", EmitDefaultValue=false)]
        public string Options { get; set; }

        /// <summary>
        /// Specify whether this is field will be mandatory on not, when being used in a subscription form. You should specify a value of either true or false. If omitted, false will be assumed.
        /// </summary>
        /// <value>Specify whether this is field will be mandatory on not, when being used in a subscription form. You should specify a value of either true or false. If omitted, false will be assumed.</value>
        [DataMember(Name="IsRequired", EmitDefaultValue=false)]
        public string IsRequired { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreatingACustomFieldRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  CustomFieldType: ").Append(CustomFieldType).Append("\n");
            sb.Append("  Options: ").Append(Options).Append("\n");
            sb.Append("  IsRequired: ").Append(IsRequired).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CreatingACustomFieldRequest);
        }

        /// <summary>
        /// Returns true if CreatingACustomFieldRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of CreatingACustomFieldRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreatingACustomFieldRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.CustomFieldType == other.CustomFieldType ||
                    this.CustomFieldType != null &&
                    this.CustomFieldType.Equals(other.CustomFieldType)
                ) && 
                (
                    this.Options == other.Options ||
                    this.Options != null &&
                    this.Options.Equals(other.Options)
                ) && 
                (
                    this.IsRequired == other.IsRequired ||
                    this.IsRequired != null &&
                    this.IsRequired.Equals(other.IsRequired)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.CustomFieldType != null)
                    hash = hash * 59 + this.CustomFieldType.GetHashCode();
                if (this.Options != null)
                    hash = hash * 59 + this.Options.GetHashCode();
                if (this.IsRequired != null)
                    hash = hash * 59 + this.IsRequired.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
