/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Moosend.Wrappers.CSharpWrapper.Client.SwaggerDateConverter;

namespace Moosend.Wrappers.CSharpWrapper.Model
{
    /// <summary>
    /// Criterion
    /// </summary>
    [DataContract]
    public partial class Criterion :  IEquatable<Criterion>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Criterion" /> class.
        /// </summary>
        /// <param name="Comparer">.</param>
        /// <param name="CustomFieldID">.</param>
        /// <param name="DateFrom">.</param>
        /// <param name="DateTo">.</param>
        /// <param name="Field">.</param>
        /// <param name="ID">.</param>
        /// <param name="Properties">.</param>
        /// <param name="SegmentID">.</param>
        /// <param name="Subscriteria">.</param>
        /// <param name="Value">.</param>
        public Criterion(double? Comparer = default(double?), string CustomFieldID = default(string), string DateFrom = default(string), string DateTo = default(string), double? Field = default(double?), double? ID = default(double?), string Properties = default(string), double? SegmentID = default(double?), string Subscriteria = default(string), string Value = default(string))
        {
            this.Comparer = Comparer;
            this.CustomFieldID = CustomFieldID;
            this.DateFrom = DateFrom;
            this.DateTo = DateTo;
            this.Field = Field;
            this.ID = ID;
            this.Properties = Properties;
            this.SegmentID = SegmentID;
            this.Subscriteria = Subscriteria;
            this.Value = Value;
        }
        
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="Comparer", EmitDefaultValue=false)]
        public double? Comparer { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="CustomFieldID", EmitDefaultValue=false)]
        public string CustomFieldID { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="DateFrom", EmitDefaultValue=false)]
        public string DateFrom { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="DateTo", EmitDefaultValue=false)]
        public string DateTo { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="Field", EmitDefaultValue=false)]
        public double? Field { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="ID", EmitDefaultValue=false)]
        public double? ID { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="Properties", EmitDefaultValue=false)]
        public string Properties { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="SegmentID", EmitDefaultValue=false)]
        public double? SegmentID { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="Subscriteria", EmitDefaultValue=false)]
        public string Subscriteria { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="Value", EmitDefaultValue=false)]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Criterion {\n");
            sb.Append("  Comparer: ").Append(Comparer).Append("\n");
            sb.Append("  CustomFieldID: ").Append(CustomFieldID).Append("\n");
            sb.Append("  DateFrom: ").Append(DateFrom).Append("\n");
            sb.Append("  DateTo: ").Append(DateTo).Append("\n");
            sb.Append("  Field: ").Append(Field).Append("\n");
            sb.Append("  ID: ").Append(ID).Append("\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("  SegmentID: ").Append(SegmentID).Append("\n");
            sb.Append("  Subscriteria: ").Append(Subscriteria).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Criterion);
        }

        /// <summary>
        /// Returns true if Criterion instances are equal
        /// </summary>
        /// <param name="other">Instance of Criterion to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Criterion other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Comparer == other.Comparer ||
                    this.Comparer != null &&
                    this.Comparer.Equals(other.Comparer)
                ) && 
                (
                    this.CustomFieldID == other.CustomFieldID ||
                    this.CustomFieldID != null &&
                    this.CustomFieldID.Equals(other.CustomFieldID)
                ) && 
                (
                    this.DateFrom == other.DateFrom ||
                    this.DateFrom != null &&
                    this.DateFrom.Equals(other.DateFrom)
                ) && 
                (
                    this.DateTo == other.DateTo ||
                    this.DateTo != null &&
                    this.DateTo.Equals(other.DateTo)
                ) && 
                (
                    this.Field == other.Field ||
                    this.Field != null &&
                    this.Field.Equals(other.Field)
                ) && 
                (
                    this.ID == other.ID ||
                    this.ID != null &&
                    this.ID.Equals(other.ID)
                ) && 
                (
                    this.Properties == other.Properties ||
                    this.Properties != null &&
                    this.Properties.Equals(other.Properties)
                ) && 
                (
                    this.SegmentID == other.SegmentID ||
                    this.SegmentID != null &&
                    this.SegmentID.Equals(other.SegmentID)
                ) && 
                (
                    this.Subscriteria == other.Subscriteria ||
                    this.Subscriteria != null &&
                    this.Subscriteria.Equals(other.Subscriteria)
                ) && 
                (
                    this.Value == other.Value ||
                    this.Value != null &&
                    this.Value.Equals(other.Value)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Comparer != null)
                    hash = hash * 59 + this.Comparer.GetHashCode();
                if (this.CustomFieldID != null)
                    hash = hash * 59 + this.CustomFieldID.GetHashCode();
                if (this.DateFrom != null)
                    hash = hash * 59 + this.DateFrom.GetHashCode();
                if (this.DateTo != null)
                    hash = hash * 59 + this.DateTo.GetHashCode();
                if (this.Field != null)
                    hash = hash * 59 + this.Field.GetHashCode();
                if (this.ID != null)
                    hash = hash * 59 + this.ID.GetHashCode();
                if (this.Properties != null)
                    hash = hash * 59 + this.Properties.GetHashCode();
                if (this.SegmentID != null)
                    hash = hash * 59 + this.SegmentID.GetHashCode();
                if (this.Subscriteria != null)
                    hash = hash * 59 + this.Subscriteria.GetHashCode();
                if (this.Value != null)
                    hash = hash * 59 + this.Value.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
