/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Moosend.Wrappers.CSharpWrapper.Client.SwaggerDateConverter;

namespace Moosend.Wrappers.CSharpWrapper.Model
{
    /// <summary>
    /// Defines Format
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Format
    {
        
        /// <summary>
        /// Enum Json for "json"
        /// </summary>
        [EnumMember(Value = "json")]
        Json,
        
        /// <summary>
        /// Enum Xml for "xml"
        /// </summary>
        [EnumMember(Value = "xml")]
        Xml
    }

}
