/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Moosend.Wrappers.CSharpWrapper.Client.SwaggerDateConverter;

namespace Moosend.Wrappers.CSharpWrapper.Model
{
    /// <summary>
    /// MailingList69
    /// </summary>
    [DataContract]
    public partial class MailingList69 :  IEquatable<MailingList69>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MailingList69" /> class.
        /// </summary>
        /// <param name="ActiveMemberCount">.</param>
        /// <param name="BouncedMemberCount">.</param>
        /// <param name="CreatedBy">.</param>
        /// <param name="CreatedOn">.</param>
        /// <param name="CustomFieldsDefinition">.</param>
        /// <param name="ID">.</param>
        /// <param name="ImportOperation">.</param>
        /// <param name="Name">.</param>
        /// <param name="RemovedMemberCount">.</param>
        /// <param name="Status">.</param>
        /// <param name="UnsubscribedMemberCount">.</param>
        /// <param name="UpdatedBy">.</param>
        /// <param name="UpdatedOn">.</param>
        public MailingList69(double? ActiveMemberCount = default(double?), double? BouncedMemberCount = default(double?), string CreatedBy = default(string), string CreatedOn = default(string), List<Object> CustomFieldsDefinition = default(List<Object>), string ID = default(string), string ImportOperation = default(string), string Name = default(string), double? RemovedMemberCount = default(double?), double? Status = default(double?), double? UnsubscribedMemberCount = default(double?), string UpdatedBy = default(string), string UpdatedOn = default(string))
        {
            this.ActiveMemberCount = ActiveMemberCount;
            this.BouncedMemberCount = BouncedMemberCount;
            this.CreatedBy = CreatedBy;
            this.CreatedOn = CreatedOn;
            this.CustomFieldsDefinition = CustomFieldsDefinition;
            this.ID = ID;
            this.ImportOperation = ImportOperation;
            this.Name = Name;
            this.RemovedMemberCount = RemovedMemberCount;
            this.Status = Status;
            this.UnsubscribedMemberCount = UnsubscribedMemberCount;
            this.UpdatedBy = UpdatedBy;
            this.UpdatedOn = UpdatedOn;
        }
        
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="ActiveMemberCount", EmitDefaultValue=false)]
        public double? ActiveMemberCount { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="BouncedMemberCount", EmitDefaultValue=false)]
        public double? BouncedMemberCount { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="CreatedBy", EmitDefaultValue=false)]
        public string CreatedBy { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="CreatedOn", EmitDefaultValue=false)]
        public string CreatedOn { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="CustomFieldsDefinition", EmitDefaultValue=false)]
        public List<Object> CustomFieldsDefinition { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="ID", EmitDefaultValue=false)]
        public string ID { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="ImportOperation", EmitDefaultValue=false)]
        public string ImportOperation { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="Name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="RemovedMemberCount", EmitDefaultValue=false)]
        public double? RemovedMemberCount { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="Status", EmitDefaultValue=false)]
        public double? Status { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="UnsubscribedMemberCount", EmitDefaultValue=false)]
        public double? UnsubscribedMemberCount { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="UpdatedBy", EmitDefaultValue=false)]
        public string UpdatedBy { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="UpdatedOn", EmitDefaultValue=false)]
        public string UpdatedOn { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MailingList69 {\n");
            sb.Append("  ActiveMemberCount: ").Append(ActiveMemberCount).Append("\n");
            sb.Append("  BouncedMemberCount: ").Append(BouncedMemberCount).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  CreatedOn: ").Append(CreatedOn).Append("\n");
            sb.Append("  CustomFieldsDefinition: ").Append(CustomFieldsDefinition).Append("\n");
            sb.Append("  ID: ").Append(ID).Append("\n");
            sb.Append("  ImportOperation: ").Append(ImportOperation).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  RemovedMemberCount: ").Append(RemovedMemberCount).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  UnsubscribedMemberCount: ").Append(UnsubscribedMemberCount).Append("\n");
            sb.Append("  UpdatedBy: ").Append(UpdatedBy).Append("\n");
            sb.Append("  UpdatedOn: ").Append(UpdatedOn).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as MailingList69);
        }

        /// <summary>
        /// Returns true if MailingList69 instances are equal
        /// </summary>
        /// <param name="other">Instance of MailingList69 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MailingList69 other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ActiveMemberCount == other.ActiveMemberCount ||
                    this.ActiveMemberCount != null &&
                    this.ActiveMemberCount.Equals(other.ActiveMemberCount)
                ) && 
                (
                    this.BouncedMemberCount == other.BouncedMemberCount ||
                    this.BouncedMemberCount != null &&
                    this.BouncedMemberCount.Equals(other.BouncedMemberCount)
                ) && 
                (
                    this.CreatedBy == other.CreatedBy ||
                    this.CreatedBy != null &&
                    this.CreatedBy.Equals(other.CreatedBy)
                ) && 
                (
                    this.CreatedOn == other.CreatedOn ||
                    this.CreatedOn != null &&
                    this.CreatedOn.Equals(other.CreatedOn)
                ) && 
                (
                    this.CustomFieldsDefinition == other.CustomFieldsDefinition ||
                    this.CustomFieldsDefinition != null &&
                    this.CustomFieldsDefinition.SequenceEqual(other.CustomFieldsDefinition)
                ) && 
                (
                    this.ID == other.ID ||
                    this.ID != null &&
                    this.ID.Equals(other.ID)
                ) && 
                (
                    this.ImportOperation == other.ImportOperation ||
                    this.ImportOperation != null &&
                    this.ImportOperation.Equals(other.ImportOperation)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.RemovedMemberCount == other.RemovedMemberCount ||
                    this.RemovedMemberCount != null &&
                    this.RemovedMemberCount.Equals(other.RemovedMemberCount)
                ) && 
                (
                    this.Status == other.Status ||
                    this.Status != null &&
                    this.Status.Equals(other.Status)
                ) && 
                (
                    this.UnsubscribedMemberCount == other.UnsubscribedMemberCount ||
                    this.UnsubscribedMemberCount != null &&
                    this.UnsubscribedMemberCount.Equals(other.UnsubscribedMemberCount)
                ) && 
                (
                    this.UpdatedBy == other.UpdatedBy ||
                    this.UpdatedBy != null &&
                    this.UpdatedBy.Equals(other.UpdatedBy)
                ) && 
                (
                    this.UpdatedOn == other.UpdatedOn ||
                    this.UpdatedOn != null &&
                    this.UpdatedOn.Equals(other.UpdatedOn)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ActiveMemberCount != null)
                    hash = hash * 59 + this.ActiveMemberCount.GetHashCode();
                if (this.BouncedMemberCount != null)
                    hash = hash * 59 + this.BouncedMemberCount.GetHashCode();
                if (this.CreatedBy != null)
                    hash = hash * 59 + this.CreatedBy.GetHashCode();
                if (this.CreatedOn != null)
                    hash = hash * 59 + this.CreatedOn.GetHashCode();
                if (this.CustomFieldsDefinition != null)
                    hash = hash * 59 + this.CustomFieldsDefinition.GetHashCode();
                if (this.ID != null)
                    hash = hash * 59 + this.ID.GetHashCode();
                if (this.ImportOperation != null)
                    hash = hash * 59 + this.ImportOperation.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.RemovedMemberCount != null)
                    hash = hash * 59 + this.RemovedMemberCount.GetHashCode();
                if (this.Status != null)
                    hash = hash * 59 + this.Status.GetHashCode();
                if (this.UnsubscribedMemberCount != null)
                    hash = hash * 59 + this.UnsubscribedMemberCount.GetHashCode();
                if (this.UpdatedBy != null)
                    hash = hash * 59 + this.UpdatedBy.GetHashCode();
                if (this.UpdatedOn != null)
                    hash = hash * 59 + this.UpdatedOn.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
