/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Moosend.Wrappers.CSharpWrapper.Client.SwaggerDateConverter;

namespace Moosend.Wrappers.CSharpWrapper.Model
{
    /// <summary>
    /// Defines ShortBy
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ShortBy
    {
        
        /// <summary>
        /// Enum Name for "Name"
        /// </summary>
        [EnumMember(Value = "Name")]
        Name,
        
        /// <summary>
        /// Enum Subject for "Subject"
        /// </summary>
        [EnumMember(Value = "Subject")]
        Subject,
        
        /// <summary>
        /// Enum Status for "Status"
        /// </summary>
        [EnumMember(Value = "Status")]
        Status,
        
        /// <summary>
        /// Enum DeliveredOn for "DeliveredOn"
        /// </summary>
        [EnumMember(Value = "DeliveredOn")]
        DeliveredOn,
        
        /// <summary>
        /// Enum CreatedOn for "CreatedOn"
        /// </summary>
        [EnumMember(Value = "CreatedOn")]
        CreatedOn
    }

}
