/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Moosend.Wrappers.CSharpWrapper.Client.SwaggerDateConverter;

namespace Moosend.Wrappers.CSharpWrapper.Model
{
    /// <summary>
    /// TestingACampaignRequest
    /// </summary>
    [DataContract]
    public partial class TestingACampaignRequest :  IEquatable<TestingACampaignRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TestingACampaignRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TestingACampaignRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TestingACampaignRequest" /> class.
        /// </summary>
        /// <param name="TestEmails">A list of email addresses to send the preview to (maximum 5 recipients). (required).</param>
        public TestingACampaignRequest(Object TestEmails = default(Object))
        {
            // to ensure "TestEmails" is required (not null)
            if (TestEmails == null)
            {
                throw new InvalidDataException("TestEmails is a required property for TestingACampaignRequest and cannot be null");
            }
            else
            {
                this.TestEmails = TestEmails;
            }
        }
        
        /// <summary>
        /// A list of email addresses to send the preview to (maximum 5 recipients).
        /// </summary>
        /// <value>A list of email addresses to send the preview to (maximum 5 recipients).</value>
        [DataMember(Name="TestEmails", EmitDefaultValue=false)]
        public Object TestEmails { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TestingACampaignRequest {\n");
            sb.Append("  TestEmails: ").Append(TestEmails).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as TestingACampaignRequest);
        }

        /// <summary>
        /// Returns true if TestingACampaignRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of TestingACampaignRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TestingACampaignRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.TestEmails == other.TestEmails ||
                    this.TestEmails != null &&
                    this.TestEmails.Equals(other.TestEmails)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.TestEmails != null)
                    hash = hash * 59 + this.TestEmails.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
