/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Moosend.Wrappers.CSharpWrapper.Client.SwaggerDateConverter;

namespace Moosend.Wrappers.CSharpWrapper.Model
{
    /// <summary>
    /// Defines Type
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Type
    {
        
        /// <summary>
        /// Enum Sent for "Sent"
        /// </summary>
        [EnumMember(Value = "Sent")]
        Sent,
        
        /// <summary>
        /// Enum Opened for "Opened"
        /// </summary>
        [EnumMember(Value = "Opened")]
        Opened,
        
        /// <summary>
        /// Enum LinkClicked for "LinkClicked"
        /// </summary>
        [EnumMember(Value = "LinkClicked")]
        LinkClicked,
        
        /// <summary>
        /// Enum Forward for "Forward"
        /// </summary>
        [EnumMember(Value = "Forward")]
        Forward,
        
        /// <summary>
        /// Enum Unsubscribed for "Unsubscribed"
        /// </summary>
        [EnumMember(Value = "Unsubscribed")]
        Unsubscribed,
        
        /// <summary>
        /// Enum Bounced for "Bounced"
        /// </summary>
        [EnumMember(Value = "Bounced")]
        Bounced
    }

}
